package types

// Applicable tags for filtering.
type ItemTagsSubSchema string

const (
	Action                    ItemTagsSubSchema = "action"
	AnimalCompanion           ItemTagsSubSchema = "animal companion"
	CharacterCreationModifier ItemTagsSubSchema = "character creation modifier"
	CriticalInjury            ItemTagsSubSchema = "critical injury"
	CrowdControl              ItemTagsSubSchema = "crowd control"
	CustomizationOption       ItemTagsSubSchema = "customization option"
	Defensive                 ItemTagsSubSchema = "defensive"
	Encounter                 ItemTagsSubSchema = "encounter"
	Factions                  ItemTagsSubSchema = "factions"
	Fear                      ItemTagsSubSchema = "fear"
	FreeManeuver              ItemTagsSubSchema = "free maneuver"
	Hacking                   ItemTagsSubSchema = "hacking"
	Incidental                ItemTagsSubSchema = "incidental"
	IncidentalOutOfTurn       ItemTagsSubSchema = "incidental (out of turn)"
	Initiative                ItemTagsSubSchema = "initiative"
	ItemQuality               ItemTagsSubSchema = "item quality"
	ItemTagsSubSchemaActive   ItemTagsSubSchema = "active"
	ItemTagsSubSchemaCombat   ItemTagsSubSchema = "combat"
	ItemTagsSubSchemaGear     ItemTagsSubSchema = "gear"
	ItemTagsSubSchemaGeneral  ItemTagsSubSchema = "general"
	ItemTagsSubSchemaMagic    ItemTagsSubSchema = "magic"
	ItemTagsSubSchemaPassive  ItemTagsSubSchema = "passive"
	ItemTagsSubSchemaSkill    ItemTagsSubSchema = "skill"
	ItemTagsSubSchemaSocial   ItemTagsSubSchema = "social"
	Leader                    ItemTagsSubSchema = "leader"
	Maneuver                  ItemTagsSubSchema = "maneuver"
	Motivation                ItemTagsSubSchema = "motivation"
	Movement                  ItemTagsSubSchema = "movement"
	Narrative                 ItemTagsSubSchema = "narrative"
	Offensive                 ItemTagsSubSchema = "offensive"
	Opposed                   ItemTagsSubSchema = "opposed"
	Recovery                  ItemTagsSubSchema = "recovery"
	Resistance                ItemTagsSubSchema = "resistance"
	ResultsModifier           ItemTagsSubSchema = "results modifier"
	ResultsSpend              ItemTagsSubSchema = "results spend"
	Session                   ItemTagsSubSchema = "session"
	SkillCheckModifier        ItemTagsSubSchema = "skill check modifier"
	StatModifier              ItemTagsSubSchema = "stat modifier"
	StatusEffect              ItemTagsSubSchema = "status effect"
	StoryPointCost            ItemTagsSubSchema = "story point cost"
	Support                   ItemTagsSubSchema = "support"
	UniqueSpell               ItemTagsSubSchema = "unique spell"
	Vehicles                  ItemTagsSubSchema = "vehicles"
	Weakness                  ItemTagsSubSchema = "weakness"
	Æmber                     ItemTagsSubSchema = "Æmber"
)
